### ISSUE TITLE
Conflict with license?

### ISSUE THREAD

**Issue by mboelen** [oshp/headers#1]
While reviewing OSHP for our [security tools](https://linuxsecurity.expert/security-tools/) section, we noticed that the project says it uses GPLv2, while the OWASP page says _"OWASP Secure Headers is free to use. It is licensed under the Apache 2.0 License"_

Is this known and correct?

**Comment by riramar** [comment]
The "OWASP Secure Headers Project" (https://www.owasp.org/index.php/OWASP_Secure_Headers_Project) is licensed under the Apache 2.0 License.
The tools "hsecscan" (https://github.com/riramar/hsecscan) and "headers" (https://github.com/oshp/headers/) are licensed under the
GNU General Public License v2.0.
